### ISSUE TITLE
Use date and time UTC to insert daily index pattern on Elasticsearch

### ISSUE THREAD

**Issue by GustavoRPS** [andreibastos/colect-stream-twitter#6]
https://github.com/andreibastos/colect-stream-twitter/blob/88f17fa10974aea8096656476be810f3972ba9a0/coletor.py#L299

Follow a exemple:
```py
from datetime import datetime
import pytz

datetime.now(tz=pytz.utc)
# datetime(2015, 6, 15, 14, 45, 19, 182703, tzinfo=<UTC>)
```

**Comment by andreibastos** [comment]
`today = str( datetime.datetime.utcnow().strftime('%Y-%m-%d'))	`
